### ISSUE TITLE
Links to readings

### ISSUE THREAD

**Issue by littleTT0704** [CoAxLab/DataSciencePsychNeuro#16]
Would it be better to add links for the required readings in the lecture pages? It will make differentiating between articles with same author easier.
I see the pdfs are in the Readings directory of this repo. (I can also create a new branch in the Data-Exploration repo to add the links?)

**Comment by coaxlab0** [comment]
Sorry, I completely missed this comment.

Good point. I'll add this to the revision list for the class.

**Comment by coaxlab0** [comment]
Resolved as links embedded in the book
